version: '3.8'

services:
  kickstart:
    image: kickstart:1.0.0
    container_name: kickstart
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3010:3000'
    hostname: kickstart
    networks:
      - taksamesh_app-network

networks:
  taksamesh_app-network:
    external: true
