version: '3.8'

services:
  kickstart:
    image: kickstart:1.0.0
    container_name: kickstart
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3010:3000'
    hostname: kickstart
    networks:
      - shared-network

networks:
  shared-network:
    external: true
